{
	"version": 1737703425,
	"fileList": [
		"data.js",
		"c2runtime.js",
		"jquery-3.4.1.min.js",
		"offlineClient.js",
		"images/redlightgreenlighthowto-sheet0.png",
		"images/redlightgreenlighthowto-sheet1.png",
		"images/redlightgreenlighthowto-sheet2.png",
		"images/play-sheet0.png",
		"images/sprite2sheet-sheet0.png",
		"images/deadmemeschest-sheet0.png",
		"images/particles.png",
		"images/group-sheet0.png",
		"images/platform-sheet0.png",
		"images/hands_0002_-sheet0.png",
		"images/hands_0003_-sheet0.png",
		"images/hands_0000_-sheet0.png",
		"images/hands_0001_-sheet0.png",
		"images/blackdot0ff1f-sheet0.png",
		"images/particles2.png",
		"media/tap.m4a",
		"media/tap.ogg",
		"media/gameover.m4a",
		"media/gameover.ogg",
		"media/good landing.m4a",
		"media/good landing.ogg",
		"media/seamless rocket.m4a",
		"media/seamless rocket.ogg",
		"media/spray.m4a",
		"media/spray.ogg",
		"media/spacex - bgm.ogg",
		"media/spacex - bgm.m4a",
		"icon-16.png",
		"icon-32.png",
		"icon-114.png",
		"icon-128.png",
		"icon-256.png",
		"loading-logo.png"
	]
}